trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    gulp
  displayName: 'npm install and run gulp'

- script: |
    yarn --cwd examples/controller install
    git checkout examples/controller/node_modules
    gulp --gulpfile examples/controller/gulpfile.js
  displayName: 'build example: controller'